---
title: "Assignment 1: Introduction"
author: "Claire Mullaney"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Salk_A03_Introduction.Rmd") prior to submission.

The completed exercise is due on Tuesday, January 14th at 1:00 pm.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: In the spring of 2017 (my final semester of undergrad), I took a Statistics for the Life Sciences course in which we used some basic r to do statistical analyses. Last semester (Fall 2019), I took Applied Data Analysis for Environmental Sciences (ENV 710) and used r more intensively to complete weekly labs. Prior to going to graduate school, I held a position as a Resolution Analyst for a tech company that included heavy troubleshooting (although we did not use R).

2. Are there any components of the course about which you feel confident?

> Answer: In ENV 710, we covered generalized linear modeling thouroughly. I felt competent in this area at the end of the semester, and I am hopeful that I will be able to confidently build on these skills.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I have some experience with data tidying in Excel, but it has been about four years since I have had to heavily manipulate data. I am looking forward to learning more about using this skill, but I am also apprehensive -- I feel like I have a lot to learn in this area.


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/cmullane94/Environmental_Data_Analytics_2020


