\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=2.54cm]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Assignment 7: GLMs week 2 (Linear Regression and beyond)},
            pdfauthor={Claire Mullaney},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Assignment 7: GLMs week 2 (Linear Regression and beyond)}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Claire Mullaney}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
    \date{}
    \predate{}\postdate{}
  

\begin{document}
\maketitle

\hypertarget{overview}{%
\subsection{OVERVIEW}\label{overview}}

This exercise accompanies the lessons in Environmental Data Analytics on
generalized linear models.

\hypertarget{directions}{%
\subsection{Directions}\label{directions}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Change ``Student Name'' on line 3 (above) with your name.
\item
  Work through the steps, \textbf{creating code and output} that fulfill
  each instruction.
\item
  Be sure to \textbf{answer the questions} in this assignment document.
\item
  When you have completed the assignment, \textbf{Knit} the text and
  code into a single PDF file.
\item
  After Knitting, submit the completed exercise (PDF file) to the
  dropbox in Sakai. Add your last name into the file name (e.g.,
  ``Salk\_A06\_GLMs\_Week1.Rmd'') prior to submission.
\end{enumerate}

The completed exercise is due on Tuesday, February 25 at 1:00 pm.

\hypertarget{set-up-your-session}{%
\subsection{Set up your session}\label{set-up-your-session}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Set up your session. Check your working directory, load the tidyverse,
  nlme, and piecewiseSEM packages, import the \emph{raw} NTL-LTER raw
  data file for chemistry/physics, and import the processed litter
  dataset. You will not work with dates, so no need to format your date
  columns this time.
\item
  Build a ggplot theme and set it as your default theme.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#1}
\CommentTok{#Loading packages and data}
\KeywordTok{getwd}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "/Users/clairemullaney/Desktop/ENV 872/Environmental_Data_Analytics_2020"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse)}
\KeywordTok{library}\NormalTok{(nlme)}
\KeywordTok{library}\NormalTok{(piecewiseSEM)}

\NormalTok{NTL_LTER <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./Data/Raw/NTL-LTER_Lake_ChemistryPhysics_Raw.csv"}\NormalTok{)}
\NormalTok{Litter <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./Data/Processed/NEON_NIWO_Litter_mass_trap_Processed.csv"}\NormalTok{)}

\CommentTok{#2}
\CommentTok{#Setting default theme}
\NormalTok{deftheme <-}\StringTok{ }\KeywordTok{theme_classic}\NormalTok{(}\DataTypeTok{base_size =} \DecValTok{14}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{color =} \StringTok{"black"}\NormalTok{), }
        \DataTypeTok{legend.position =} \StringTok{"right"}\NormalTok{)}
\KeywordTok{theme_set}\NormalTok{(deftheme)}
\end{Highlighting}
\end{Shaded}

\hypertarget{ntl-lter-test}{%
\subsection{NTL-LTER test}\label{ntl-lter-test}}

Research question: What is the best set of predictors for lake
temperatures in July across the monitoring period at the North Temperate
Lakes LTER?

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Wrangle your NTL-LTER dataset with a pipe function so that it contains
  only the following criteria:
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Only dates in July (hint: use the daynum column). No need to consider
  leap years.
\item
  Only the columns: lakename, year4, daynum, depth, temperature\_C
\item
  Only complete cases (i.e., remove NAs)
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Run an AIC to determine what set of explanatory variables (year4,
  daynum, depth) is best suited to predict temperature. Run a multiple
  regression on the recommended set of variables.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#3}
\CommentTok{#Filtering by dates in July, selecting relevant columns, and removing NAs}

\NormalTok{NTL_LTER_wr <-}\StringTok{ }
\StringTok{  }\NormalTok{NTL_LTER }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(daynum }\OperatorTok{>=}\StringTok{ }\DecValTok{182} \OperatorTok{&}\StringTok{ }\NormalTok{daynum }\OperatorTok{<=}\StringTok{ }\DecValTok{212}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(lakename, year4, daynum, depth, temperature_C) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{na.omit}\NormalTok{()}
  
\CommentTok{#4}
\CommentTok{#Determing the best multiple linear regression model for predicting temperature}

\NormalTok{TempAIC <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ NTL_LTER_wr, temperature_C }\OperatorTok{~}\StringTok{ }\NormalTok{year4 }\OperatorTok{+}\StringTok{ }\NormalTok{daynum }\OperatorTok{+}\StringTok{ }\NormalTok{depth)}

\KeywordTok{step}\NormalTok{(TempAIC)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Start:  AIC=26016.31
## temperature_C ~ year4 + daynum + depth
## 
##          Df Sum of Sq    RSS   AIC
## <none>                141118 26016
## - year4   1        80 141198 26020
## - daynum  1      1333 142450 26106
## - depth   1    403925 545042 39151
\end{verbatim}

\begin{verbatim}
## 
## Call:
## lm(formula = temperature_C ~ year4 + daynum + depth, data = NTL_LTER_wr)
## 
## Coefficients:
## (Intercept)        year4       daynum        depth  
##    -6.45556      0.01013      0.04134     -1.94726
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Temp <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ NTL_LTER_wr, temperature_C }\OperatorTok{~}\StringTok{ }\NormalTok{year4 }\OperatorTok{+}\StringTok{ }\NormalTok{daynum }\OperatorTok{+}\StringTok{ }\NormalTok{depth)}

\KeywordTok{summary}\NormalTok{(Temp)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = temperature_C ~ year4 + daynum + depth, data = NTL_LTER_wr)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.6517 -2.9937  0.0855  2.9692 13.6171 
## 
## Coefficients:
##              Estimate Std. Error  t value Pr(>|t|)    
## (Intercept) -6.455560   8.638808   -0.747   0.4549    
## year4        0.010131   0.004303    2.354   0.0186 *  
## daynum       0.041336   0.004315    9.580   <2e-16 ***
## depth       -1.947264   0.011676 -166.782   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.811 on 9718 degrees of freedom
## Multiple R-squared:  0.7417, Adjusted R-squared:  0.7417 
## F-statistic:  9303 on 3 and 9718 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  What is the final set of explanatory variables that predict
  temperature from your multiple regression? How much of the observed
  variance does this model explain?
\end{enumerate}

\begin{quote}
Answer: According to the AIC analysis, the final set of explanatory
variables that predict temperature includes year4 (year), daynum
(numerical day of the year), and depth. This model explains 74.17\% of
the observed variance in temperature.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  Run an interaction effects ANCOVA to predict temperature based on
  depth and lakename from the same wrangled dataset.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#6}

\NormalTok{Temp}\FloatTok{.2}\NormalTok{ <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ NTL_LTER_wr, temperature_C }\OperatorTok{~}\StringTok{ }\NormalTok{depth }\OperatorTok{*}\StringTok{ }\NormalTok{lakename)}

\KeywordTok{summary}\NormalTok{(Temp}\FloatTok{.2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = temperature_C ~ depth * lakename, data = NTL_LTER_wr)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.6455 -2.9133 -0.2879  2.7567 16.3606 
## 
## Coefficients:
##                                Estimate Std. Error t value Pr(>|t|)    
## (Intercept)                     22.9455     0.5861  39.147  < 2e-16 ***
## depth                           -2.5820     0.2411 -10.711  < 2e-16 ***
## lakenameCrampton Lake            2.2173     0.6804   3.259  0.00112 ** 
## lakenameEast Long Lake          -4.3884     0.6191  -7.089 1.45e-12 ***
## lakenameHummingbird Lake        -2.4126     0.8379  -2.879  0.00399 ** 
## lakenamePaul Lake                0.6105     0.5983   1.020  0.30754    
## lakenamePeter Lake               0.2998     0.5970   0.502  0.61552    
## lakenameTuesday Lake            -2.8932     0.6060  -4.774 1.83e-06 ***
## lakenameWard Lake                2.4180     0.8434   2.867  0.00415 ** 
## lakenameWest Long Lake          -2.4663     0.6168  -3.999 6.42e-05 ***
## depth:lakenameCrampton Lake      0.8058     0.2465   3.268  0.00109 ** 
## depth:lakenameEast Long Lake     0.9465     0.2433   3.891  0.00010 ***
## depth:lakenameHummingbird Lake  -0.6026     0.2919  -2.064  0.03903 *  
## depth:lakenamePaul Lake          0.4022     0.2421   1.662  0.09664 .  
## depth:lakenamePeter Lake         0.5799     0.2418   2.398  0.01649 *  
## depth:lakenameTuesday Lake       0.6605     0.2426   2.723  0.00648 ** 
## depth:lakenameWard Lake         -0.6930     0.2862  -2.421  0.01548 *  
## depth:lakenameWest Long Lake     0.8154     0.2431   3.354  0.00080 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.471 on 9704 degrees of freedom
## Multiple R-squared:  0.7861, Adjusted R-squared:  0.7857 
## F-statistic:  2097 on 17 and 9704 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\tightlist
\item
  Is there a significant interaction between depth and lakename? How
  much variance in the temperature observations does this explain?
\end{enumerate}

\begin{quote}
Answer: Yes, there is a significant interaction between depth and
lakename. For the overall model, p \textless{} 0.0001, and most of the
individual interaction terms in the model (e.g., the interaction between
depth and Peter Lake) significantly affect temperature. A model that
uses the interaction effects between depth and lakename to predict
temperature explains 78.57\% of the observed variance in temperature.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  Create a graph that depicts temperature by depth, with a separate
  color for each lake. Add a geom\_smooth (method = ``lm'', se = FALSE)
  for each lake. Make your points 50 \% transparent. Adjust your y axis
  limits to go from 0 to 35 degrees. Clean up your graph to make it
  pretty.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#8}
\CommentTok{#Creating a graph of temperature vs. depth}
\NormalTok{temp.depth <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ NTL_LTER_wr, }
                     \KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ depth, }\DataTypeTok{y =}\NormalTok{ temperature_C, }\DataTypeTok{color =}\NormalTok{ lakename)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{se =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{"Depth (m)"}\NormalTok{, }\DataTypeTok{y =} \KeywordTok{expression}\NormalTok{(}\StringTok{"Temperature "}\NormalTok{ (degree}\OperatorTok{~}\NormalTok{C)), }
       \DataTypeTok{color =} \StringTok{""}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{35}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{scale_color_viridis_d}\NormalTok{()}

\KeywordTok{print}\NormalTok{(temp.depth)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A07_GLMs_Week2_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\tightlist
\item
  Run a mixed effects model to predict dry mass of litter. We already
  know that nlcdClass and functionalGroup have a significant
  interaction, so we will specify those two variables as fixed effects
  with an interaction. We also know that litter mass varies across plot
  ID, but we are less interested in the actual effect of the plot itself
  but rather in accounting for the variance among plots. Plot ID will be
  our random effect.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Build and run a mixed effects model.
\item
  Check the difference between the marginal and conditional R2 of the
  model.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Mixed effects model}
\NormalTok{dryMass.lme <-}\StringTok{ }\KeywordTok{lme}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ Litter, }
\NormalTok{              dryMass }\OperatorTok{~}\StringTok{ }\NormalTok{nlcdClass }\OperatorTok{*}\StringTok{ }\NormalTok{functionalGroup, }
              \DataTypeTok{random =} \OperatorTok{~}\DecValTok{1}\OperatorTok{|}\NormalTok{plotID)}

\KeywordTok{summary}\NormalTok{(dryMass.lme)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Linear mixed-effects model fit by REML
##  Data: Litter 
##        AIC      BIC    logLik
##   9038.575 9179.479 -4493.287
## 
## Random effects:
##  Formula: ~1 | plotID
##         (Intercept) Residual
## StdDev:   0.5899105 3.456817
## 
## Fixed effects: dryMass ~ nlcdClass * functionalGroup 
##                                                                Value
## (Intercept)                                                 0.155492
## nlcdClassgrasslandHerbaceous                               -0.156004
## nlcdClassshrubScrub                                        -0.107080
## functionalGroupLeaves                                      -0.126008
## functionalGroupMixed                                        1.477797
## functionalGroupNeedles                                      7.284064
## functionalGroupOther                                       -0.048525
## functionalGroupSeeds                                       -0.058702
## functionalGroupTwigs/branches                               1.929441
## functionalGroupWoody material                               1.068772
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves          0.181416
## nlcdClassshrubScrub:functionalGroupLeaves                   0.173857
## nlcdClassgrasslandHerbaceous:functionalGroupMixed          -0.467648
## nlcdClassshrubScrub:functionalGroupMixed                    0.633876
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles        -2.118299
## nlcdClassshrubScrub:functionalGroupNeedles                 -2.909142
## nlcdClassgrasslandHerbaceous:functionalGroupOther           0.143603
## nlcdClassshrubScrub:functionalGroupOther                    0.104935
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds           0.049290
## nlcdClassshrubScrub:functionalGroupSeeds                    0.076708
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches -0.986627
## nlcdClassshrubScrub:functionalGroupTwigs/branches          -1.503446
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material -1.017803
## nlcdClassshrubScrub:functionalGroupWoody material          -0.979078
##                                                            Std.Error   DF
## (Intercept)                                                0.4863580 1659
## nlcdClassgrasslandHerbaceous                               0.7789816    9
## nlcdClassshrubScrub                                        0.6636775    9
## functionalGroupLeaves                                      0.5501061 1659
## functionalGroupMixed                                       0.6323043 1659
## functionalGroupNeedles                                     0.5313161 1659
## functionalGroupOther                                       0.5500878 1659
## functionalGroupSeeds                                       0.5501061 1659
## functionalGroupTwigs/branches                              0.5385556 1659
## functionalGroupWoody material                              0.5259330 1659
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves         0.8847246 1659
## nlcdClassshrubScrub:functionalGroupLeaves                  0.7510320 1659
## nlcdClassgrasslandHerbaceous:functionalGroupMixed          1.1201304 1659
## nlcdClassshrubScrub:functionalGroupMixed                   0.9217911 1659
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles        0.8705440 1659
## nlcdClassshrubScrub:functionalGroupNeedles                 0.7347172 1659
## nlcdClassgrasslandHerbaceous:functionalGroupOther          0.8976715 1659
## nlcdClassshrubScrub:functionalGroupOther                   0.7528434 1659
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds          0.8976827 1659
## nlcdClassshrubScrub:functionalGroupSeeds                   0.7547591 1659
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches 0.8850639 1659
## nlcdClassshrubScrub:functionalGroupTwigs/branches          0.7409024 1659
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material 0.8802289 1659
## nlcdClassshrubScrub:functionalGroupWoody material          0.7317033 1659
##                                                              t-value
## (Intercept)                                                 0.319706
## nlcdClassgrasslandHerbaceous                               -0.200266
## nlcdClassshrubScrub                                        -0.161343
## functionalGroupLeaves                                      -0.229061
## functionalGroupMixed                                        2.337160
## functionalGroupNeedles                                     13.709474
## functionalGroupOther                                       -0.088213
## functionalGroupSeeds                                       -0.106711
## functionalGroupTwigs/branches                               3.582622
## functionalGroupWoody material                               2.032144
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves          0.205053
## nlcdClassshrubScrub:functionalGroupLeaves                   0.231490
## nlcdClassgrasslandHerbaceous:functionalGroupMixed          -0.417495
## nlcdClassshrubScrub:functionalGroupMixed                    0.687657
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles        -2.433305
## nlcdClassshrubScrub:functionalGroupNeedles                 -3.959540
## nlcdClassgrasslandHerbaceous:functionalGroupOther           0.159972
## nlcdClassshrubScrub:functionalGroupOther                    0.139385
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds           0.054908
## nlcdClassshrubScrub:functionalGroupSeeds                    0.101632
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches -1.114752
## nlcdClassshrubScrub:functionalGroupTwigs/branches          -2.029209
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material -1.156293
## nlcdClassshrubScrub:functionalGroupWoody material          -1.338081
##                                                            p-value
## (Intercept)                                                 0.7492
## nlcdClassgrasslandHerbaceous                                0.8457
## nlcdClassshrubScrub                                         0.8754
## functionalGroupLeaves                                       0.8188
## functionalGroupMixed                                        0.0195
## functionalGroupNeedles                                      0.0000
## functionalGroupOther                                        0.9297
## functionalGroupSeeds                                        0.9150
## functionalGroupTwigs/branches                               0.0003
## functionalGroupWoody material                               0.0423
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves          0.8376
## nlcdClassshrubScrub:functionalGroupLeaves                   0.8170
## nlcdClassgrasslandHerbaceous:functionalGroupMixed           0.6764
## nlcdClassshrubScrub:functionalGroupMixed                    0.4918
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles         0.0151
## nlcdClassshrubScrub:functionalGroupNeedles                  0.0001
## nlcdClassgrasslandHerbaceous:functionalGroupOther           0.8729
## nlcdClassshrubScrub:functionalGroupOther                    0.8892
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds           0.9562
## nlcdClassshrubScrub:functionalGroupSeeds                    0.9191
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches  0.2651
## nlcdClassshrubScrub:functionalGroupTwigs/branches           0.0426
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material  0.2477
## nlcdClassshrubScrub:functionalGroupWoody material           0.1811
##  Correlation: 
##                                                            (Intr) nlcdCH
## nlcdClassgrasslandHerbaceous                               -0.624       
## nlcdClassshrubScrub                                        -0.733  0.458
## functionalGroupLeaves                                      -0.559  0.349
## functionalGroupMixed                                       -0.485  0.303
## functionalGroupNeedles                                     -0.579  0.361
## functionalGroupOther                                       -0.559  0.349
## functionalGroupSeeds                                       -0.559  0.349
## functionalGroupTwigs/branches                              -0.571  0.356
## functionalGroupWoody material                              -0.584  0.365
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves          0.347 -0.586
## nlcdClassshrubScrub:functionalGroupLeaves                   0.409 -0.255
## nlcdClassgrasslandHerbaceous:functionalGroupMixed           0.274 -0.462
## nlcdClassshrubScrub:functionalGroupMixed                    0.333 -0.208
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles         0.353 -0.595
## nlcdClassshrubScrub:functionalGroupNeedles                  0.418 -0.261
## nlcdClassgrasslandHerbaceous:functionalGroupOther           0.342 -0.577
## nlcdClassshrubScrub:functionalGroupOther                    0.408 -0.255
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds           0.342 -0.577
## nlcdClassshrubScrub:functionalGroupSeeds                    0.407 -0.254
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches  0.347 -0.586
## nlcdClassshrubScrub:functionalGroupTwigs/branches           0.415 -0.259
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material  0.349 -0.589
## nlcdClassshrubScrub:functionalGroupWoody material           0.420 -0.262
##                                                            nlcdCS fnctGL
## nlcdClassgrasslandHerbaceous                                            
## nlcdClassshrubScrub                                                     
## functionalGroupLeaves                                       0.409       
## functionalGroupMixed                                        0.356  0.429
## functionalGroupNeedles                                      0.424  0.511
## functionalGroupOther                                        0.409  0.494
## functionalGroupSeeds                                        0.409  0.494
## functionalGroupTwigs/branches                               0.418  0.504
## functionalGroupWoody material                               0.428  0.516
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves         -0.255 -0.622
## nlcdClassshrubScrub:functionalGroupLeaves                  -0.569 -0.732
## nlcdClassgrasslandHerbaceous:functionalGroupMixed          -0.201 -0.242
## nlcdClassshrubScrub:functionalGroupMixed                   -0.464 -0.295
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles        -0.259 -0.312
## nlcdClassshrubScrub:functionalGroupNeedles                 -0.582 -0.370
## nlcdClassgrasslandHerbaceous:functionalGroupOther          -0.251 -0.303
## nlcdClassshrubScrub:functionalGroupOther                   -0.568 -0.361
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds          -0.251 -0.303
## nlcdClassshrubScrub:functionalGroupSeeds                   -0.566 -0.360
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches -0.254 -0.307
## nlcdClassshrubScrub:functionalGroupTwigs/branches          -0.577 -0.367
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material -0.256 -0.309
## nlcdClassshrubScrub:functionalGroupWoody material          -0.584 -0.371
##                                                            fnctGM fnctGN
## nlcdClassgrasslandHerbaceous                                            
## nlcdClassshrubScrub                                                     
## functionalGroupLeaves                                                   
## functionalGroupMixed                                                    
## functionalGroupNeedles                                      0.445       
## functionalGroupOther                                        0.430  0.511
## functionalGroupSeeds                                        0.429  0.511
## functionalGroupTwigs/branches                               0.439  0.522
## functionalGroupWoody material                               0.449  0.535
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves         -0.267 -0.318
## nlcdClassshrubScrub:functionalGroupLeaves                  -0.314 -0.374
## nlcdClassgrasslandHerbaceous:functionalGroupMixed          -0.564 -0.251
## nlcdClassshrubScrub:functionalGroupMixed                   -0.686 -0.305
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles        -0.272 -0.610
## nlcdClassshrubScrub:functionalGroupNeedles                 -0.322 -0.723
## nlcdClassgrasslandHerbaceous:functionalGroupOther          -0.263 -0.313
## nlcdClassshrubScrub:functionalGroupOther                   -0.314 -0.374
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds          -0.263 -0.313
## nlcdClassshrubScrub:functionalGroupSeeds                   -0.313 -0.373
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches -0.267 -0.318
## nlcdClassshrubScrub:functionalGroupTwigs/branches          -0.319 -0.380
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material -0.268 -0.320
## nlcdClassshrubScrub:functionalGroupWoody material          -0.322 -0.384
##                                                            fnctGO fnctGS
## nlcdClassgrasslandHerbaceous                                            
## nlcdClassshrubScrub                                                     
## functionalGroupLeaves                                                   
## functionalGroupMixed                                                    
## functionalGroupNeedles                                                  
## functionalGroupOther                                                    
## functionalGroupSeeds                                        0.494       
## functionalGroupTwigs/branches                               0.504  0.504
## functionalGroupWoody material                               0.516  0.517
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves         -0.307 -0.307
## nlcdClassshrubScrub:functionalGroupLeaves                  -0.362 -0.362
## nlcdClassgrasslandHerbaceous:functionalGroupMixed          -0.243 -0.242
## nlcdClassshrubScrub:functionalGroupMixed                   -0.295 -0.294
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles        -0.312 -0.312
## nlcdClassshrubScrub:functionalGroupNeedles                 -0.370 -0.370
## nlcdClassgrasslandHerbaceous:functionalGroupOther          -0.613 -0.303
## nlcdClassshrubScrub:functionalGroupOther                   -0.731 -0.361
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds          -0.303 -0.613
## nlcdClassshrubScrub:functionalGroupSeeds                   -0.360 -0.729
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches -0.307 -0.307
## nlcdClassshrubScrub:functionalGroupTwigs/branches          -0.367 -0.367
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material -0.309 -0.309
## nlcdClassshrubScrub:functionalGroupWoody material          -0.371 -0.371
##                                                            fncGT/ fncGWm
## nlcdClassgrasslandHerbaceous                                            
## nlcdClassshrubScrub                                                     
## functionalGroupLeaves                                                   
## functionalGroupMixed                                                    
## functionalGroupNeedles                                                  
## functionalGroupOther                                                    
## functionalGroupSeeds                                                    
## functionalGroupTwigs/branches                                           
## functionalGroupWoody material                               0.528       
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves         -0.314 -0.321
## nlcdClassshrubScrub:functionalGroupLeaves                  -0.369 -0.378
## nlcdClassgrasslandHerbaceous:functionalGroupMixed          -0.248 -0.253
## nlcdClassshrubScrub:functionalGroupMixed                   -0.301 -0.308
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles        -0.319 -0.326
## nlcdClassshrubScrub:functionalGroupNeedles                 -0.378 -0.387
## nlcdClassgrasslandHerbaceous:functionalGroupOther          -0.309 -0.316
## nlcdClassshrubScrub:functionalGroupOther                   -0.369 -0.377
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds          -0.309 -0.317
## nlcdClassshrubScrub:functionalGroupSeeds                   -0.368 -0.376
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches -0.608 -0.321
## nlcdClassshrubScrub:functionalGroupTwigs/branches          -0.727 -0.384
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material -0.315 -0.597
## nlcdClassshrubScrub:functionalGroupWoody material          -0.379 -0.719
##                                                            nCH:GL nCS:GL
## nlcdClassgrasslandHerbaceous                                            
## nlcdClassshrubScrub                                                     
## functionalGroupLeaves                                                   
## functionalGroupMixed                                                    
## functionalGroupNeedles                                                  
## functionalGroupOther                                                    
## functionalGroupSeeds                                                    
## functionalGroupTwigs/branches                                           
## functionalGroupWoody material                                           
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves                      
## nlcdClassshrubScrub:functionalGroupLeaves                   0.455       
## nlcdClassgrasslandHerbaceous:functionalGroupMixed           0.406  0.178
## nlcdClassshrubScrub:functionalGroupMixed                    0.183  0.410
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles         0.524  0.229
## nlcdClassshrubScrub:functionalGroupNeedles                  0.230  0.514
## nlcdClassgrasslandHerbaceous:functionalGroupOther           0.508  0.222
## nlcdClassshrubScrub:functionalGroupOther                    0.224  0.502
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds           0.508  0.222
## nlcdClassshrubScrub:functionalGroupSeeds                    0.224  0.500
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches  0.515  0.225
## nlcdClassshrubScrub:functionalGroupTwigs/branches           0.228  0.510
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material  0.518  0.226
## nlcdClassshrubScrub:functionalGroupWoody material           0.231  0.516
##                                                            nCH:GM nCS:GM
## nlcdClassgrasslandHerbaceous                                            
## nlcdClassshrubScrub                                                     
## functionalGroupLeaves                                                   
## functionalGroupMixed                                                    
## functionalGroupNeedles                                                  
## functionalGroupOther                                                    
## functionalGroupSeeds                                                    
## functionalGroupTwigs/branches                                           
## functionalGroupWoody material                                           
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves                      
## nlcdClassshrubScrub:functionalGroupLeaves                               
## nlcdClassgrasslandHerbaceous:functionalGroupMixed                       
## nlcdClassshrubScrub:functionalGroupMixed                    0.387       
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles         0.414  0.186
## nlcdClassshrubScrub:functionalGroupNeedles                  0.182  0.419
## nlcdClassgrasslandHerbaceous:functionalGroupOther           0.401  0.181
## nlcdClassshrubScrub:functionalGroupOther                    0.177  0.409
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds           0.402  0.180
## nlcdClassshrubScrub:functionalGroupSeeds                    0.177  0.408
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches  0.407  0.183
## nlcdClassshrubScrub:functionalGroupTwigs/branches           0.180  0.416
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material  0.409  0.184
## nlcdClassshrubScrub:functionalGroupWoody material           0.182  0.420
##                                                            nCH:GN nCS:GN
## nlcdClassgrasslandHerbaceous                                            
## nlcdClassshrubScrub                                                     
## functionalGroupLeaves                                                   
## functionalGroupMixed                                                    
## functionalGroupNeedles                                                  
## functionalGroupOther                                                    
## functionalGroupSeeds                                                    
## functionalGroupTwigs/branches                                           
## functionalGroupWoody material                                           
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves                      
## nlcdClassshrubScrub:functionalGroupLeaves                               
## nlcdClassgrasslandHerbaceous:functionalGroupMixed                       
## nlcdClassshrubScrub:functionalGroupMixed                                
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles                     
## nlcdClassshrubScrub:functionalGroupNeedles                  0.441       
## nlcdClassgrasslandHerbaceous:functionalGroupOther           0.517  0.227
## nlcdClassshrubScrub:functionalGroupOther                    0.228  0.513
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds           0.517  0.227
## nlcdClassshrubScrub:functionalGroupSeeds                    0.227  0.512
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches  0.524  0.230
## nlcdClassshrubScrub:functionalGroupTwigs/branches           0.232  0.521
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material  0.527  0.231
## nlcdClassshrubScrub:functionalGroupWoody material           0.235  0.528
##                                                            nCH:GO nCS:GO
## nlcdClassgrasslandHerbaceous                                            
## nlcdClassshrubScrub                                                     
## functionalGroupLeaves                                                   
## functionalGroupMixed                                                    
## functionalGroupNeedles                                                  
## functionalGroupOther                                                    
## functionalGroupSeeds                                                    
## functionalGroupTwigs/branches                                           
## functionalGroupWoody material                                           
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves                      
## nlcdClassshrubScrub:functionalGroupLeaves                               
## nlcdClassgrasslandHerbaceous:functionalGroupMixed                       
## nlcdClassshrubScrub:functionalGroupMixed                                
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles                     
## nlcdClassshrubScrub:functionalGroupNeedles                              
## nlcdClassgrasslandHerbaceous:functionalGroupOther                       
## nlcdClassshrubScrub:functionalGroupOther                    0.448       
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds           0.501  0.221
## nlcdClassshrubScrub:functionalGroupSeeds                    0.221  0.499
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches  0.508  0.224
## nlcdClassshrubScrub:functionalGroupTwigs/branches           0.225  0.509
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material  0.511  0.225
## nlcdClassshrubScrub:functionalGroupWoody material           0.227  0.515
##                                                            nCH:GS nCS:GS
## nlcdClassgrasslandHerbaceous                                            
## nlcdClassshrubScrub                                                     
## functionalGroupLeaves                                                   
## functionalGroupMixed                                                    
## functionalGroupNeedles                                                  
## functionalGroupOther                                                    
## functionalGroupSeeds                                                    
## functionalGroupTwigs/branches                                           
## functionalGroupWoody material                                           
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves                      
## nlcdClassshrubScrub:functionalGroupLeaves                               
## nlcdClassgrasslandHerbaceous:functionalGroupMixed                       
## nlcdClassshrubScrub:functionalGroupMixed                                
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles                     
## nlcdClassshrubScrub:functionalGroupNeedles                              
## nlcdClassgrasslandHerbaceous:functionalGroupOther                       
## nlcdClassshrubScrub:functionalGroupOther                                
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds                       
## nlcdClassshrubScrub:functionalGroupSeeds                    0.447       
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches  0.508  0.224
## nlcdClassshrubScrub:functionalGroupTwigs/branches           0.225  0.507
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material  0.511  0.225
## nlcdClassshrubScrub:functionalGroupWoody material           0.228  0.514
##                                                            nCH:GT nCS:GT
## nlcdClassgrasslandHerbaceous                                            
## nlcdClassshrubScrub                                                     
## functionalGroupLeaves                                                   
## functionalGroupMixed                                                    
## functionalGroupNeedles                                                  
## functionalGroupOther                                                    
## functionalGroupSeeds                                                    
## functionalGroupTwigs/branches                                           
## functionalGroupWoody material                                           
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves                      
## nlcdClassshrubScrub:functionalGroupLeaves                               
## nlcdClassgrasslandHerbaceous:functionalGroupMixed                       
## nlcdClassshrubScrub:functionalGroupMixed                                
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles                     
## nlcdClassshrubScrub:functionalGroupNeedles                              
## nlcdClassgrasslandHerbaceous:functionalGroupOther                       
## nlcdClassshrubScrub:functionalGroupOther                                
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds                       
## nlcdClassshrubScrub:functionalGroupSeeds                                
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches              
## nlcdClassshrubScrub:functionalGroupTwigs/branches           0.442       
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material  0.518  0.229
## nlcdClassshrubScrub:functionalGroupWoody material           0.231  0.523
##                                                            nCH:Gm
## nlcdClassgrasslandHerbaceous                                     
## nlcdClassshrubScrub                                              
## functionalGroupLeaves                                            
## functionalGroupMixed                                             
## functionalGroupNeedles                                           
## functionalGroupOther                                             
## functionalGroupSeeds                                             
## functionalGroupTwigs/branches                                    
## functionalGroupWoody material                                    
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves               
## nlcdClassshrubScrub:functionalGroupLeaves                        
## nlcdClassgrasslandHerbaceous:functionalGroupMixed                
## nlcdClassshrubScrub:functionalGroupMixed                         
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles              
## nlcdClassshrubScrub:functionalGroupNeedles                       
## nlcdClassgrasslandHerbaceous:functionalGroupOther                
## nlcdClassshrubScrub:functionalGroupOther                         
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds                
## nlcdClassshrubScrub:functionalGroupSeeds                         
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches       
## nlcdClassshrubScrub:functionalGroupTwigs/branches                
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material       
## nlcdClassshrubScrub:functionalGroupWoody material           0.429
## 
## Standardized Within-Group Residuals:
##         Min          Q1         Med          Q3         Max 
## -1.96496855 -0.23842984 -0.01535880  0.09027291 14.27434811 
## 
## Number of Observations: 1692
## Number of Groups: 12
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Marginal r-squared: fixed effects}
\CommentTok{#Conditional r-quared: r-squared when you add in the random effects}
\KeywordTok{rsquared}\NormalTok{(dryMass.lme)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Response   family     link method  Marginal Conditional
## 1  dryMass gaussian identity   none 0.2465822   0.2679023
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  continued\ldots{} How much more variance is explained by adding the
  random effect to the model?
\end{enumerate}

\begin{quote}
Answer: About 2\% (more exactly, 2.132\%) more variance is explained by
adding the random effect to the model; the fixed effects explain about
24.658\% of the variance and the fixed and random effects explain about
26.790\%.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Run the same model without the random effect.
\item
  Run an anova on the two tests.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Same model without random effect}
\NormalTok{dryMass.lm <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ Litter, }
\NormalTok{              dryMass }\OperatorTok{~}\StringTok{ }\NormalTok{nlcdClass }\OperatorTok{*}\StringTok{ }\NormalTok{functionalGroup)}

\KeywordTok{summary}\NormalTok{(dryMass.lm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = dryMass ~ nlcdClass * functionalGroup, data = Litter)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -6.612 -0.480 -0.058 -0.005 49.051 
## 
## Coefficients:
##                                                            Estimate
## (Intercept)                                                 0.11963
## nlcdClassgrasslandHerbaceous                               -0.11420
## nlcdClassshrubScrub                                        -0.10412
## functionalGroupLeaves                                      -0.10360
## functionalGroupMixed                                        1.50475
## functionalGroupNeedles                                      7.31226
## functionalGroupOther                                       -0.03482
## functionalGroupSeeds                                       -0.04616
## functionalGroupTwigs/branches                               1.95967
## functionalGroupWoody material                               1.08431
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves          0.12865
## nlcdClassshrubScrub:functionalGroupLeaves                   0.14703
## nlcdClassgrasslandHerbaceous:functionalGroupMixed          -0.38118
## nlcdClassshrubScrub:functionalGroupMixed                    0.74593
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles        -2.13880
## nlcdClassshrubScrub:functionalGroupNeedles                 -2.92148
## nlcdClassgrasslandHerbaceous:functionalGroupOther           0.12606
## nlcdClassshrubScrub:functionalGroupOther                    0.08589
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds           0.04615
## nlcdClassshrubScrub:functionalGroupSeeds                    0.05944
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches -1.01519
## nlcdClassshrubScrub:functionalGroupTwigs/branches          -1.49559
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material -1.04086
## nlcdClassshrubScrub:functionalGroupWoody material          -0.97185
##                                                            Std. Error
## (Intercept)                                                   0.39070
## nlcdClassgrasslandHerbaceous                                  0.64223
## nlcdClassshrubScrub                                           0.53838
## functionalGroupLeaves                                         0.55606
## functionalGroupMixed                                          0.63800
## functionalGroupNeedles                                        0.53696
## functionalGroupOther                                          0.55606
## functionalGroupSeeds                                          0.55606
## functionalGroupTwigs/branches                                 0.54434
## functionalGroupWoody material                                 0.53156
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves            0.89410
## nlcdClassshrubScrub:functionalGroupLeaves                     0.75915
## nlcdClassgrasslandHerbaceous:functionalGroupMixed             1.13024
## nlcdClassshrubScrub:functionalGroupMixed                      0.93038
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles           0.87993
## nlcdClassshrubScrub:functionalGroupNeedles                    0.74258
## nlcdClassgrasslandHerbaceous:functionalGroupOther             0.90743
## nlcdClassshrubScrub:functionalGroupOther                      0.76101
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds             0.90743
## nlcdClassshrubScrub:functionalGroupSeeds                      0.76295
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches    0.89462
## nlcdClassshrubScrub:functionalGroupTwigs/branches             0.74881
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material    0.88971
## nlcdClassshrubScrub:functionalGroupWoody material             0.73957
##                                                            t value
## (Intercept)                                                  0.306
## nlcdClassgrasslandHerbaceous                                -0.178
## nlcdClassshrubScrub                                         -0.193
## functionalGroupLeaves                                       -0.186
## functionalGroupMixed                                         2.359
## functionalGroupNeedles                                      13.618
## functionalGroupOther                                        -0.063
## functionalGroupSeeds                                        -0.083
## functionalGroupTwigs/branches                                3.600
## functionalGroupWoody material                                2.040
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves           0.144
## nlcdClassshrubScrub:functionalGroupLeaves                    0.194
## nlcdClassgrasslandHerbaceous:functionalGroupMixed           -0.337
## nlcdClassshrubScrub:functionalGroupMixed                     0.802
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles         -2.431
## nlcdClassshrubScrub:functionalGroupNeedles                  -3.934
## nlcdClassgrasslandHerbaceous:functionalGroupOther            0.139
## nlcdClassshrubScrub:functionalGroupOther                     0.113
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds            0.051
## nlcdClassshrubScrub:functionalGroupSeeds                     0.078
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches  -1.135
## nlcdClassshrubScrub:functionalGroupTwigs/branches           -1.997
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material  -1.170
## nlcdClassshrubScrub:functionalGroupWoody material           -1.314
##                                                            Pr(>|t|)    
## (Intercept)                                                0.759502    
## nlcdClassgrasslandHerbaceous                               0.858888    
## nlcdClassshrubScrub                                        0.846673    
## functionalGroupLeaves                                      0.852224    
## functionalGroupMixed                                       0.018462 *  
## functionalGroupNeedles                                      < 2e-16 ***
## functionalGroupOther                                       0.950081    
## functionalGroupSeeds                                       0.933846    
## functionalGroupTwigs/branches                              0.000327 ***
## functionalGroupWoody material                              0.041519 *  
## nlcdClassgrasslandHerbaceous:functionalGroupLeaves         0.885611    
## nlcdClassshrubScrub:functionalGroupLeaves                  0.846453    
## nlcdClassgrasslandHerbaceous:functionalGroupMixed          0.735969    
## nlcdClassshrubScrub:functionalGroupMixed                   0.422814    
## nlcdClassgrasslandHerbaceous:functionalGroupNeedles        0.015177 *  
## nlcdClassshrubScrub:functionalGroupNeedles                 8.69e-05 ***
## nlcdClassgrasslandHerbaceous:functionalGroupOther          0.889531    
## nlcdClassshrubScrub:functionalGroupOther                   0.910155    
## nlcdClassgrasslandHerbaceous:functionalGroupSeeds          0.959441    
## nlcdClassshrubScrub:functionalGroupSeeds                   0.937915    
## nlcdClassgrasslandHerbaceous:functionalGroupTwigs/branches 0.256634    
## nlcdClassshrubScrub:functionalGroupTwigs/branches          0.045956 *  
## nlcdClassgrasslandHerbaceous:functionalGroupWoody material 0.242213    
## nlcdClassshrubScrub:functionalGroupWoody material          0.189001    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.494 on 1668 degrees of freedom
## Multiple R-squared:  0.2516, Adjusted R-squared:  0.2413 
## F-statistic: 24.38 on 23 and 1668 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Comparing the results of the two models}
\KeywordTok{anova}\NormalTok{(dryMass.lme, dryMass.lm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             Model df      AIC      BIC    logLik   Test  L.Ratio p-value
## dryMass.lme     1 26 9038.575 9179.479 -4493.287                        
## dryMass.lm      2 25 9058.088 9193.573 -4504.044 1 vs 2 21.51338  <.0001
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  continued\ldots{} Is the mixed effects model a better model than the
  fixed effects model? How do you know?
\end{enumerate}

\begin{quote}
Answer: The mixed effects model is better than the fixed effects model;
its AIC is lower by a value of about 20. The p-value for the comparison
of the two models is \textless{}.0001, confirming that this lower AIC
value indicates that the mixed effects model has a significantly
different (and, in this case, better) fit than the fixed effects model.
\end{quote}


\end{document}
